# ===============================
# Kubernetes Ingress Resource
# ===============================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coderco-task-manager-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: www.tecknosap.co.uk
      http:
        paths:
          # ===============================
          # Root Path Routing Rule
          # ===============================
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coderco-task-manager-service
                port:
                  number: 80
